// src/lib/aqlLexicon/types.js


export const RM_TYPES = [
  "COMPOSITION", "SECTION", "ADMIN_ENTRY",
  "OBSERVATION", "EVALUATION", "INSTRUCTION",
  "ACTION", "CLUSTER", "ITEM_TREE", "ITEM_LIST",
  "ITEM_SINGLE", "ITEM_TABLE", "ELEMENT", "HISTORY",
  "EVENT", "POINT_EVENT", "INTERVAL_EVENT", "ACTIVITY",
  "ISM_TRANSITION", "INSTRUCTION_DETAILS", "CARE_ENTRY",
  "PARTY_PROXY", "EVENT_CONTEXT"
]

export const AQL_RM_ENTRY_TYPES = ['OBSERVATION','EVALUATION','INSTRUCTION','ACTION','ADMIN_ENTRY'];
export const AQL_RM_CONTAINER_TYPES = ['EHR','COMPOSITION','SECTION', ...AQL_RM_ENTRY_TYPES, 'CLUSTER'];
  
export const AQL_DATAVALUE_TYPES = [
  'DV_TEXT','DV_CODED_TEXT','DV_QUANTITY','DV_COUNT','DV_DATE_TIME','DV_DATE','DV_TIME',
  'DV_BOOLEAN','DV_IDENTIFIER','DV_ORDINAL','DV_URI','DV_MULTIMEDIA','DV_PARSABLE',
  'DV_DURATION','DV_PROPORTION','DV_INTERVAL','DV_STATE'
];

export const AQL_SELECTABLE_TYPES = new Set([ ...AQL_DATAVALUE_TYPES, 'COMPOSITION','SECTION', ...AQL_RM_ENTRY_TYPES,'CLUSTER' ]);
export const AQL_FILTERABLE_TYPES = new Set(AQL_DATAVALUE_TYPES);
export const AQL_ORDERABLE_TYPES = new Set(['DV_TEXT','DV_CODED_TEXT','DV_QUANTITY','DV_COUNT','DV_DATE_TIME','DV_DATE','DV_TIME','DV_ORDINAL','DV_IDENTIFIER']);
