export const AGENTIC_COPILOT_STRATEGY = {
  id: 'agentic.healthcare.context_objects',
  name: 'Agentic Copilots over ContextObjects',
  version: '0.1.0',
  summary:
    'A strategy family for ContextObject design, deterministic retrieval, semantic products, answer models, and control-plane evaluation.',
  docs: {
    overview: [
      {
        id: 'kehrnel-docs-index',
        title: 'Kehrnel docs index',
        summary: 'Entry point to the execution-kernel documentation for HDL integrations and the new ContextObjects stack.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/README.md',
        topics: ['overview', 'navigation', 'execution kernel'],
      },
      {
        id: 'hdl-kehrnel-contract',
        title: 'HDL ↔ Kehrnel contract',
        summary: 'Broad contract between HDL as the studio and kehrnel as the runtime execution kernel.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/hdl-contract.md',
        topics: ['runtime ownership', 'apis', 'activation', 'query'],
      },
    ],
    contextObjects: [
      {
        id: 'contextobjects-runtime-overview',
        title: 'ContextObjects runtime overview',
        summary: 'Explains the shared runtime contracts for ContextObject definitions, resolution, and executable retrieval.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/contextobjects-runtime-overview.md',
        topics: ['definitions', 'resolver', 'runtime models'],
      },
      {
        id: 'hdl-kehrnel-contextobjects-contract',
        title: 'HDL ↔ Kehrnel ContextObjects contract',
        summary: 'Defines the authoring-versus-execution split and the runtime seam for ContextObjects, Con2L, and Context Maps.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/hdl-kehrnel-contextobjects-contract.md',
        topics: ['hdl', 'kehrnel', 'contracts'],
      },
      {
        id: 'tenant-context-catalog',
        title: 'Tenant context catalog publication',
        summary: 'Explains how HDL publishes normalized tenant ContextObject definitions for kehrnel runtime resolution.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/tenant-context-catalog-publication.md',
        topics: ['publication', 'tenant catalog', 'definitions'],
      },
    ],
    retrieval: [
      {
        id: 'con2l-runtime',
        title: 'Con2L negotiation and runtime',
        summary: 'Documents draft, resolved, and executable Con2L stages and how they compile to deterministic plans.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/con2l-negotiation-and-runtime.md',
        topics: ['Con2L', 'negotiation', 'query compilation'],
      },
      {
        id: 'strategy-ops',
        title: 'ContextObject strategy ops',
        summary: 'Lists the shared runtime ops HDL can call on ContextObject-shaped strategies.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/contextobjects-strategy-ops.md',
        topics: ['ops', 'resolve_context_contract', 'compile_con2l', 'negotiate_con2l'],
      },
      {
        id: 'tenant-context-catalog-retrieval',
        title: 'Tenant catalog publication',
        summary: 'Shows how Con2L resolution can load tenant-published ContextObject definitions when inline contracts are not passed.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/tenant-context-catalog-publication.md',
        topics: ['catalog loading', 'published definitions', 'resolution'],
      },
    ],
    factory: [
      {
        id: 'objectmaps-runtime',
        title: 'Context Maps runtime',
        summary: 'Explains Context Map execution contracts and the current summary-first runtime support.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/objectmaps-runtime.md',
        topics: ['Context Maps', 'mapping', 'execution'],
      },
      {
        id: 'synthetic-contract',
        title: 'Synthetic contract',
        summary: 'Current HDL ↔ kehrnel synthetic-generation contract for runtime jobs and batch outputs.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/hdl-kehrnel-synthetic-contract-v2.md',
        topics: ['synthetic', 'jobs', 'generation'],
      },
    ],
    copilots: [
      {
        id: 'hdl-kehrnel-contextobjects-contract-copilots',
        title: 'ContextObjects seam for copilots',
        summary: 'Shows how Con2L and ContextObjects sit below semantic products and answer models.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/hdl-kehrnel-contextobjects-contract.md',
        topics: ['copilots', 'context contracts', 'semantic products'],
      },
      {
        id: 'con2l-runtime-copilots',
        title: 'Con2L runtime for copilots',
        summary: 'Explains the shared negotiation core that direct retrieval and copilots can both reuse.',
        path: '/Users/francesc.mateu/Documents/GitHub/kehrnel/docs/con2l-negotiation-and-runtime.md',
        topics: ['shared core', 'Request IR', 'negotiation'],
      },
    ],
  },
  contractResolution: {
    summary:
      'Natural language first resolves against the modeled ContextObject universe before branching into direct Con2L retrieval or full copilot answer orchestration.',
    steps: [
      {
        id: 'request-ir',
        name: 'Request IR',
        description: 'Capture subject, scope, temporal window, question family, aggregation, and comparison hints.',
      },
      {
        id: 'context-contract',
        name: 'Context contract resolution',
        description:
          'Match the request against ContextObject definitions, blocks, terminology bindings, assertion types, and relation-aware context signals.',
      },
      {
        id: 'branch',
        name: 'Execution branch',
        description:
          'Resolve either to Con2L for deterministic retrieval or to a semantic product for multi-step copilot execution.',
      },
    ],
    capabilities: [
      {
        id: 'terminology',
        name: 'Terminology expansion',
        description: 'Use code systems, descriptions, synonyms, and local aliases to broaden candidate matching safely.',
      },
      {
        id: 'relations',
        name: 'Relation-aware resolution',
        description: 'Use parent-child, sibling, temporal, and workflow relations to disambiguate similar data points.',
      },
      {
        id: 'assertions',
        name: 'Assertion typing',
        description: 'Differentiate observed, derived, workflow, and guidance assertions before contract compilation.',
      },
      {
        id: 'embeddings',
        name: 'Embedding enrichment',
        description: 'Use embedding lookup and reranking as supportive enrichment, not as the final contract authority.',
      },
      {
        id: 'clarification',
        name: 'Negotiated clarification',
        description: 'Escalate to clarification when confidence or evidence is too weak for deterministic compilation.',
      },
    ],
    hardProblems: [
      'Choosing between sibling data points that share similar labels but differ by parent path or workflow state.',
      'Resolving a requested assertion to observed versus derived data when both are available.',
      'Using terminology descriptions and embeddings without letting fuzzy retrieval override contract safety.',
      'Compiling cross-subject requests while preserving subject anchors, window semantics, and governance rules.',
    ],
  },
  contextContracts: [
    {
      id: 'oncology_episode_context',
      name: 'Oncology Episode Context',
      contextType: 'subject',
      anchor: 'patient',
      temporalMode: 'episode',
      contains: ['identity', 'timeline', 'diagnostic evidence', 'protocol bindings'],
      retrievalModes: ['context_lookup', 'semantic_search'],
      enrichment: ['SNOMED descriptions', 'local aliases', 'evidence rerank'],
    },
    {
      id: 'followup_population_context',
      name: 'Follow-up Population Context',
      contextType: 'population',
      anchor: 'center',
      temporalMode: 'windowed',
      contains: ['workflow steps', 'delay metrics', 'cohort slices'],
      retrievalModes: ['analytics', 'cross_subject'],
      enrichment: ['workflow relations', 'time-window constraints'],
    },
    {
      id: 'clinical_review_workbench_context',
      name: 'Clinical Review Workbench Context',
      contextType: 'agentic',
      anchor: 'patient',
      temporalMode: 'mixed',
      contains: ['task state', 'evidence bundle', 'pending gaps', 'notes'],
      retrievalModes: ['agentic', 'context_lookup'],
      enrichment: ['agent memory', 'relationship scoring', 'clarification state'],
    },
  ],
  factory: {
    generationRecipes: [
      {
        id: 'episode_recipe',
        name: 'Episode scenario recipe',
        purpose: 'Generate subject-level episode contexts with timelines, evidence, and workflow transitions.',
        outputs: ['ContextObject instances', 'subject case instances', 'agentic workbench seeds'],
      },
      {
        id: 'population_recipe',
        name: 'Population benchmark recipe',
        purpose: 'Generate cross-subject distributions, bottlenecks, and center-level benchmark materializations.',
        outputs: ['population instances', 'analytics-ready snapshots', 'coverage scenarios'],
      },
      {
        id: 'copilot_regression_recipe',
        name: 'Copilot regression recipe',
        purpose: 'Generate stable scenario packs tied to personas, question families, and expected answer behavior.',
        outputs: ['evaluation library rows', 'expected human answers', 'request-shape assertions'],
      },
    ],
    contextMaps: [
      {
        id: 'objectmap.cda.tumour_summary',
        name: 'Tumour summary Context Map',
        source: 'CDA tumour summary',
        target: 'Oncology Episode Context',
        blocks: ['Identity Block', 'Temporal Event Block', 'Terminology Binding Block'],
        outcome: 'Canonical subject context instance',
      },
      {
        id: 'objectmap.csv.followup_worklist',
        name: 'Follow-up worklist Context Map',
        source: 'Operational CSV / scheduling feed',
        target: 'Follow-up Population Context',
        blocks: ['Workflow Step Block', 'Risk Signal Block', 'Provenance Block'],
        outcome: 'Population context instances + benchmark-ready snapshots',
      },
    ],
    mappingRecipes: [
      {
        id: 'source_to_context_object',
        name: 'Context Map recipe',
        purpose: 'Map incoming source documents into ContextObject definitions and reusable blocks.',
        stages: ['identify source type', 'bind terminology', 'map to blocks', 'compose context instance'],
      },
      {
        id: 'legacy_to_agentic_context',
        name: 'Legacy uplift recipe',
        purpose: 'Lift legacy healthcare documents into contexts suitable for Con2L and semantic products.',
        stages: ['extract anchors', 'resolve assertion type', 'attach provenance', 'publish governed instance'],
      },
    ],
    scenarioPacks: [
      {
        id: 'scenario.followup_delay.hotspots',
        name: 'Follow-up delay hotspot pack',
        emits: ['ContextObject instances', 'population instance slice', 'evaluation questions'],
        usedBy: ['followup_delay_distribution', 'care_pathway_bottleneck_review'],
      },
      {
        id: 'scenario.protocol_guidance.case_review',
        name: 'Protocol guidance case review pack',
        emits: ['subject context', 'evidence bundle', 'expected human answer'],
        usedBy: ['trial_protocol_alignment_review', 'protocol_guidance'],
      },
      {
        id: 'scenario.screening_funnel.operations',
        name: 'Screening funnel operations pack',
        emits: ['cross-subject instances', 'analytics snapshot', 'role-based questions'],
        usedBy: ['screening_to_biopsy_conversion', 'program_overview'],
      },
    ],
  },
  instances: [
    {
      id: 'subject_case_instance',
      name: 'Subject Case Instance',
      scope: 'subject',
      purpose: 'Realized context for one patient, one battery, or one case assembled from definitions and blocks.',
      outputs: ['identity', 'status summary', 'timeline events', 'top risks'],
    },
    {
      id: 'population_context_instance',
      name: 'Population Context Instance',
      scope: 'population',
      purpose: 'Cross-subject context instance used for distributions, worklists, and benchmark summaries.',
      outputs: ['kpis', 'cohort slices', 'rankings', 'operational signals'],
    },
    {
      id: 'agentic_workbench_instance',
      name: 'Agentic Workbench Instance',
      scope: 'agentic',
      purpose: 'Working context instance for review sessions, unresolved demand, and multi-step investigations.',
      outputs: ['task context', 'evidence bundle', 'pending gaps', 'trace state'],
    },
  ],
  blocks: [
    {
      id: 'block.identity.v1',
      name: 'Identity Block',
      kind: 'anchor',
      purpose: 'Reusable subject identity and external identifiers.',
      fields: ['subjectId', 'externalIds', 'mrn', 'deviceSerial'],
    },
    {
      id: 'block.temporal_event.v1',
      name: 'Temporal Event Block',
      kind: 'time',
      purpose: 'Reusable event shape for episode, workflow, and timeline contexts.',
      fields: ['eventTime', 'eventType', 'status', 'actor'],
    },
    {
      id: 'block.terminology_binding.v1',
      name: 'Terminology Binding Block',
      kind: 'binding',
      purpose: 'Terminology and code bindings for controlled concepts.',
      fields: ['code', 'system', 'display', 'version'],
    },
    {
      id: 'block.provenance.v1',
      name: 'Provenance Block',
      kind: 'governance',
      purpose: 'Lineage, source references, and ingestion metadata.',
      fields: ['sourceType', 'sourceId', 'capturedAt', 'confidence'],
    },
    {
      id: 'block.workflow_step.v1',
      name: 'Workflow Step Block',
      kind: 'workflow',
      purpose: 'Task state used in operational and agentic contexts.',
      fields: ['step', 'owner', 'deadline', 'resolution'],
    },
    {
      id: 'block.risk_signal.v1',
      name: 'Risk Signal Block',
      kind: 'signal',
      purpose: 'Reusable pattern for derived or observed risk cues.',
      fields: ['signalName', 'severity', 'evidence', 'trend'],
    },
  ],
  retrieval: {
    pillars: [
      {
        id: 'aql',
        name: 'AQL / openEHR',
        purpose: 'Structured openEHR querying where AQL is the natural contract.',
      },
      {
        id: 'fhir',
        name: 'FHIR Retrieval',
        purpose: 'Resource retrieval and projection for FHIR-native strategies.',
      },
      {
        id: 'context',
        name: 'ContextObject Retrieval',
        purpose: 'Direct subject or population retrieval over ContextObject instances.',
      },
      {
        id: 'con2l',
        name: 'Con2L',
        purpose: 'Conversation-to-context contract language with negotiated states before deterministic execution.',
      },
    ],
    con2lStages: [
      {
        id: 'draft',
        name: 'Draft',
        description: 'Natural language has been interpreted into a tentative context request.',
      },
      {
        id: 'resolved',
        name: 'Resolved',
        description: 'The request is matched to ContextObjects, data points, assertion types, and allowed scopes.',
      },
      {
        id: 'executable',
        name: 'Executable',
        description: 'The request is fully constrained and can compile into deterministic retrieval.',
      },
    ],
    examples: [
      {
        id: 'con2l-delay',
        title: 'Follow-up delay distribution',
        naturalLanguage: 'How are suspicious-case follow-up delays distributed this quarter by center?',
        resolvedTo: 'Follow-up Population Context + aggregate distribution + center grouping + quarter window',
        disambiguation: 'delay is resolved through workflow-step relations and quarter window semantics',
      },
      {
        id: 'con2l-protocol',
        title: 'Protocol guidance',
        naturalLanguage: 'What protocol guidance should we follow for next diagnostic steps?',
        resolvedTo: 'Oncology Episode Context + protocol knowledge + guidance answer contract',
        disambiguation: 'protocol is resolved as a guidance assertion, not just a note or timeline event',
      },
      {
        id: 'con2l-timeline',
        title: 'Timeline retrieval',
        naturalLanguage: 'Show this patient timeline and defect sequence.',
        resolvedTo: 'Clinical Review Workbench Context + temporal series + issue path emphasis',
        disambiguation: 'timeline uses temporal and parent-child relations to prefer event-sequence nodes over profile facts',
      },
    ],
    con2lArtifacts: [
      {
        id: 'artifact.followup_delay_distribution',
        title: 'Follow-up delay distribution',
        draft: {
          subject: 'population',
          ask: 'distribution',
          focus: ['follow-up delay'],
          groupBy: ['center'],
          window: 'this quarter',
        },
        resolved: {
          contextContract: 'followup_population_context',
          assertionType: 'workflow',
          predicates: ['contains workflow steps', 'window quarter', 'group by center'],
          retrievalMode: 'analytics',
        },
        executable: {
          dialect: 'con2l/v1',
          from: 'followup_population_context',
          where: [{ predicate: 'delay_type', op: 'eq', value: 'followup' }],
          groupBy: ['center'],
          aggregate: 'distribution',
          window: { type: 'calendar_quarter', value: 'current' },
        },
      },
      {
        id: 'artifact.protocol_guidance_case',
        title: 'Protocol guidance case review',
        draft: {
          subject: 'patient',
          ask: 'guidance',
          focus: ['next diagnostic steps'],
          evidence: ['protocol', 'current case'],
        },
        resolved: {
          contextContract: 'oncology_episode_context',
          assertionType: 'guidance',
          predicates: ['contains diagnostic evidence', 'bind protocol knowledge'],
          retrievalMode: 'context_lookup',
        },
        executable: {
          dialect: 'con2l/v1',
          from: 'oncology_episode_context',
          contains: ['diagnostic_evidence', 'protocol_guidance'],
          subject: { anchor: 'patient', source: 'current_scope' },
          output: 'guidance_bundle',
        },
      },
    ],
  },
  copilots: {
    questionLibrary: [
      {
        id: 'q1',
        role: 'Scheduling manager',
        family: 'distribution',
        question: 'Show the appointment status distribution across all centers.',
        expectedProduct: 'appointment_status_distribution',
        answerModel: 'distribution_answer',
      },
      {
        id: 'q2',
        role: 'Radiology operations',
        family: 'distribution',
        question: 'How is the current screening volume distributed across BI-RADS categories?',
        expectedProduct: 'birads_distribution',
        answerModel: 'distribution_answer',
      },
      {
        id: 'q3',
        role: 'Program analyst',
        family: 'bottleneck',
        question: 'Where are the main follow-up delays this quarter?',
        expectedProduct: 'followup_delay_distribution',
        answerModel: 'analysis_answer',
      },
      {
        id: 'q4',
        role: 'Trial navigator',
        family: 'alignment',
        question: 'Which active clinical trials best match this case and why?',
        expectedProduct: 'trial_protocol_alignment_review',
        answerModel: 'evidence_answer',
      },
      {
        id: 'q5',
        role: 'Clinical reviewer',
        family: 'case-summary',
        question: 'Summarize the diagnostic risk from screening, biopsy, and notes.',
        expectedProduct: 'diagnostic_risk_summary',
        answerModel: 'status_answer',
      },
      {
        id: 'q6',
        role: 'Operations lead',
        family: 'benchmark',
        question: 'Compare suspicious-case follow-up delays by center this quarter.',
        expectedProduct: 'center_benchmark_summary',
        answerModel: 'benchmark_answer',
      },
    ],
    semanticProducts: [
      {
        id: 'patient_case_summary',
        purpose: 'Summarize one subject case with grounded context and next-best actions.',
        requires: ['subject context', 'timeline', 'risk signals'],
        route: 'Patient workspace',
        answerModel: 'status_answer',
      },
      {
        id: 'diagnostic_risk_summary',
        purpose: 'Explain why a case is risky using imaging, pathology, and narrative evidence.',
        requires: ['subject context', 'diagnostic evidence', 'risk signals'],
        route: 'Patient workspace',
        answerModel: 'status_answer',
      },
      {
        id: 'followup_delay_distribution',
        purpose: 'Show distribution of follow-up delays across a requested population.',
        requires: ['population view', 'delay metrics'],
        route: 'Operations analytics',
        answerModel: 'distribution_answer',
      },
      {
        id: 'care_pathway_bottleneck_review',
        purpose: 'Explain pathway bottlenecks, main blockers, and affected populations.',
        requires: ['population view', 'workflow steps', 'time deltas'],
        route: 'Operations analytics',
        answerModel: 'analysis_answer',
      },
      {
        id: 'trial_protocol_alignment_review',
        purpose: 'Relate trial eligibility and protocol guidance to the current case.',
        requires: ['subject context', 'protocol knowledge', 'trial evidence'],
        route: 'Clinical guidance',
        answerModel: 'evidence_answer',
      },
    ],
    toolsAndPlans: [
      {
        id: 'assemble_subject_context',
        type: 'tool',
        purpose: 'Resolve one subject case context from ContextObject instances.',
        usedBy: ['patient_case_summary', 'diagnostic_risk_summary'],
      },
      {
        id: 'analyze_population_distribution',
        type: 'tool',
        purpose: 'Compute grouped distributions and cohort summaries.',
        usedBy: ['followup_delay_distribution'],
      },
      {
        id: 'analyze_pathway_bottlenecks',
        type: 'tool',
        purpose: 'Compute operational bottlenecks, step delays, and hotspots.',
        usedBy: ['care_pathway_bottleneck_review'],
      },
      {
        id: 'review_trial_protocol_alignment',
        type: 'tool',
        purpose: 'Combine patient context with trial and protocol evidence.',
        usedBy: ['trial_protocol_alignment_review'],
      },
      {
        id: 'subject_context_plan',
        type: 'plan',
        purpose: 'Resolve anchor, load subject view, enrich with evidence, answer.',
        usedBy: ['patient_case_summary', 'diagnostic_risk_summary'],
      },
      {
        id: 'population_distribution_plan',
        type: 'plan',
        purpose: 'Resolve scope, load population view, aggregate, render chart payload.',
        usedBy: ['followup_delay_distribution'],
      },
    ],
    answerModels: [
      {
        id: 'status_answer',
        lead: 'Open with the answer and state the main risk or status plainly.',
        widgets: ['status pill', 'fact strip', 'timeline preview'],
        handoff: 'Patient workspace',
      },
      {
        id: 'distribution_answer',
        lead: 'Open with the requested spread and name the dominant segment.',
        widgets: ['distribution chart', 'kpi strip'],
        handoff: 'Analytics workspace',
      },
      {
        id: 'benchmark_answer',
        lead: 'Open with the comparison delta and highlight the leader or laggard.',
        widgets: ['benchmark cards', 'comparison chart'],
        handoff: 'Analytics workspace',
      },
      {
        id: 'evidence_answer',
        lead: 'Open with the best-supported conclusion and then cite why.',
        widgets: ['evidence cluster', 'support references'],
        handoff: 'Evidence workspace',
      },
      {
        id: 'analysis_answer',
        lead: 'Lead with the main bottleneck or operational finding.',
        widgets: ['ranked list', 'kpis', 'trend or heat chart'],
        handoff: 'Operations workspace',
      },
    ],
    controlPlane: [
      {
        id: 'question-coverage',
        name: 'Question coverage',
        description: 'Tracks which personas, families, and products are covered in the evaluation library.',
      },
      {
        id: 'product-readiness',
        name: 'Product readiness',
        description: 'Scores semantic products by answer quality, grounding, and gap diagnostics.',
      },
      {
        id: 'retrieval-determinism',
        name: 'Retrieval determinism',
        description: 'Measures how often NLQ resolves cleanly to ContextObjects, Con2L, and plans.',
      },
      {
        id: 'generation-coverage',
        name: 'Synthetic coverage',
        description: 'Tracks how much of the strategy can be exercised with synthetic data and scenario packs.',
      },
    ],
  },
};

export const AGENTIC_COPILOT_SUMMARY = {
  instances: AGENTIC_COPILOT_STRATEGY.instances.length,
  blocks: AGENTIC_COPILOT_STRATEGY.blocks.length,
  retrievalPillars: AGENTIC_COPILOT_STRATEGY.retrieval.pillars.length,
  questions: AGENTIC_COPILOT_STRATEGY.copilots.questionLibrary.length,
  products: AGENTIC_COPILOT_STRATEGY.copilots.semanticProducts.length,
  toolsAndPlans: AGENTIC_COPILOT_STRATEGY.copilots.toolsAndPlans.length,
  answerModels: AGENTIC_COPILOT_STRATEGY.copilots.answerModels.length,
  controlPlanePillars: AGENTIC_COPILOT_STRATEGY.copilots.controlPlane.length,
};
